# Generated by Django 4.2.2 on 2023-07-20 11:27

import EduNova.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_remove_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('74beb5a6-f13e-41a1-9895-bd7b2c824b7d'), primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('header', models.CharField(max_length=30)),
                ('head', models.BooleanField(default=False)),
                ('next_article', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EduNova.article')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('uuid', models.UUIDField(default=uuid.UUID('15e40462-e21a-48f0-a893-22d51357d6bf'), primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', EduNova.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('de2871b6-d1a3-4aec-93de-89bfc06511a0'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('percent', models.FloatField(default=0.0)),
                ('uuid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('topics', models.ManyToManyField(to='EduNova.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('24a9ccf9-7535-49a2-8637-7ce7590b10f3'), editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('uuid_article', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='EduNova.article')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('9501950f-156c-47e8-9d80-4cc22217550b'), editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('uuid_topic', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='EduNova.topic')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='uuid_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduNova.topic'),
        ),
    ]
